apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: advert
  description: Сервис рекламных объявлений
  annotations:
    github.com/project-slug: s21platform/advert-service  # Укажите правильный репозиторий
  #    backstage.io/techdocs-ref: dir:.  # Если планируете использовать TechDocs
  tags:
    - grpc
#  links:
#    - url: потом добавить ссылку на метрики графаны
#      title: Grafana
#      icon: dashboard
spec:
  type: service
  lifecycle: production
  owner: advert-service-team  # GitHub-логин ответственного
  providesApis:
    - Advert-v0
#  consumesApis:
#    - optionhub-api
#  dependsOn:
#    - component:optionhub
#  system: authentication-system  # Можно указать систему, если есть