// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.26.1
// source: api/advert.proto

package advert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdvertEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdvertEmpty) Reset() {
	*x = AdvertEmpty{}
	mi := &file_api_advert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertEmpty) ProtoMessage() {}

func (x *AdvertEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_api_advert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertEmpty.ProtoReflect.Descriptor instead.
func (*AdvertEmpty) Descriptor() ([]byte, []int) {
	return file_api_advert_proto_rawDescGZIP(), []int{0}
}

type AdvertText struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TextContent string                 `protobuf:"bytes,1,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	ExpiredAt   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
}

func (x *AdvertText) Reset() {
	*x = AdvertText{}
	mi := &file_api_advert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdvertText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertText) ProtoMessage() {}

func (x *AdvertText) ProtoReflect() protoreflect.Message {
	mi := &file_api_advert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertText.ProtoReflect.Descriptor instead.
func (*AdvertText) Descriptor() ([]byte, []int) {
	return file_api_advert_proto_rawDescGZIP(), []int{1}
}

func (x *AdvertText) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *AdvertText) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

type GetAdvertsOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Adverts []*AdvertText `protobuf:"bytes,1,rep,name=adverts,proto3" json:"adverts,omitempty"`
}

func (x *GetAdvertsOut) Reset() {
	*x = GetAdvertsOut{}
	mi := &file_api_advert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdvertsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertsOut) ProtoMessage() {}

func (x *GetAdvertsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_advert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertsOut.ProtoReflect.Descriptor instead.
func (*GetAdvertsOut) Descriptor() ([]byte, []int) {
	return file_api_advert_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdvertsOut) GetAdverts() []*AdvertText {
	if x != nil {
		return x.Adverts
	}
	return nil
}

type UserFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Os []int64 `protobuf:"varint,1,rep,packed,name=os,proto3" json:"os,omitempty"`
}

func (x *UserFilter) Reset() {
	*x = UserFilter{}
	mi := &file_api_advert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFilter) ProtoMessage() {}

func (x *UserFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_advert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFilter.ProtoReflect.Descriptor instead.
func (*UserFilter) Descriptor() ([]byte, []int) {
	return file_api_advert_proto_rawDescGZIP(), []int{3}
}

func (x *UserFilter) GetOs() []int64 {
	if x != nil {
		return x.Os
	}
	return nil
}

type CreateAdvertIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text      string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	User      *UserFilter            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	ExpiredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
}

func (x *CreateAdvertIn) Reset() {
	*x = CreateAdvertIn{}
	mi := &file_api_advert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdvertIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertIn) ProtoMessage() {}

func (x *CreateAdvertIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_advert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertIn.ProtoReflect.Descriptor instead.
func (*CreateAdvertIn) Descriptor() ([]byte, []int) {
	return file_api_advert_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAdvertIn) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *CreateAdvertIn) GetUser() *UserFilter {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateAdvertIn) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

type CancelAdvertIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CancelAdvertIn) Reset() {
	*x = CancelAdvertIn{}
	mi := &file_api_advert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAdvertIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAdvertIn) ProtoMessage() {}

func (x *CancelAdvertIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_advert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAdvertIn.ProtoReflect.Descriptor instead.
func (*CancelAdvertIn) Descriptor() ([]byte, []int) {
	return file_api_advert_proto_rawDescGZIP(), []int{5}
}

func (x *CancelAdvertIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RestoreAdvertIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RestoreAdvertIn) Reset() {
	*x = RestoreAdvertIn{}
	mi := &file_api_advert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreAdvertIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreAdvertIn) ProtoMessage() {}

func (x *RestoreAdvertIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_advert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreAdvertIn.ProtoReflect.Descriptor instead.
func (*RestoreAdvertIn) Descriptor() ([]byte, []int) {
	return file_api_advert_proto_rawDescGZIP(), []int{6}
}

func (x *RestoreAdvertIn) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EditAdvertIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TextContent string      `protobuf:"bytes,2,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	UserFilter  *UserFilter `protobuf:"bytes,3,opt,name=user_filter,json=userFilter,proto3" json:"user_filter,omitempty"`
}

func (x *EditAdvertIn) Reset() {
	*x = EditAdvertIn{}
	mi := &file_api_advert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAdvertIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAdvertIn) ProtoMessage() {}

func (x *EditAdvertIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_advert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAdvertIn.ProtoReflect.Descriptor instead.
func (*EditAdvertIn) Descriptor() ([]byte, []int) {
	return file_api_advert_proto_rawDescGZIP(), []int{7}
}

func (x *EditAdvertIn) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EditAdvertIn) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *EditAdvertIn) GetUserFilter() *UserFilter {
	if x != nil {
		return x.UserFilter
	}
	return nil
}

var File_api_advert_proto protoreflect.FileDescriptor

var file_api_advert_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a, 0x0b, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x22, 0x6a, 0x0a, 0x0a, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x22, 0x36,
	0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x12,
	0x25, 0x0a, 0x07, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0b, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x07, 0x61,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x73, 0x22, 0x1c, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03,
	0x52, 0x02, 0x6f, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x39, 0x0a, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x64, 0x41, 0x74, 0x22, 0x20, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x52, 0x65, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6f, 0x0a, 0x0c,
	0x45, 0x64, 0x69, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x74, 0x65, 0x78, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x2c, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x32, 0xff, 0x01,
	0x0a, 0x0d, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x2c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x73, 0x12, 0x0c, 0x2e,
	0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x0e, 0x2e, 0x47, 0x65,
	0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x73, 0x4f, 0x75, 0x74, 0x22, 0x00, 0x12, 0x2f, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x12, 0x0f, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x1a, 0x0c,
	0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x2f,
	0x0a, 0x0c, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x12, 0x0f,
	0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x1a,
	0x0c, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x31, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x12, 0x10, 0x2e, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x49, 0x6e, 0x1a, 0x0c, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x2b, 0x0a, 0x0a, 0x45, 0x64, 0x69, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x12, 0x0d, 0x2e, 0x45, 0x64, 0x69, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x49, 0x6e, 0x1a,
	0x0c, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_advert_proto_rawDescOnce sync.Once
	file_api_advert_proto_rawDescData = file_api_advert_proto_rawDesc
)

func file_api_advert_proto_rawDescGZIP() []byte {
	file_api_advert_proto_rawDescOnce.Do(func() {
		file_api_advert_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_advert_proto_rawDescData)
	})
	return file_api_advert_proto_rawDescData
}

var file_api_advert_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_advert_proto_goTypes = []any{
	(*AdvertEmpty)(nil),           // 0: AdvertEmpty
	(*AdvertText)(nil),            // 1: AdvertText
	(*GetAdvertsOut)(nil),         // 2: GetAdvertsOut
	(*UserFilter)(nil),            // 3: UserFilter
	(*CreateAdvertIn)(nil),        // 4: CreateAdvertIn
	(*CancelAdvertIn)(nil),        // 5: CancelAdvertIn
	(*RestoreAdvertIn)(nil),       // 6: RestoreAdvertIn
	(*EditAdvertIn)(nil),          // 7: EditAdvertIn
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_api_advert_proto_depIdxs = []int32{
	8,  // 0: AdvertText.expired_at:type_name -> google.protobuf.Timestamp
	1,  // 1: GetAdvertsOut.adverts:type_name -> AdvertText
	3,  // 2: CreateAdvertIn.user:type_name -> UserFilter
	8,  // 3: CreateAdvertIn.expired_at:type_name -> google.protobuf.Timestamp
	3,  // 4: EditAdvertIn.user_filter:type_name -> UserFilter
	0,  // 5: AdvertService.GetAdverts:input_type -> AdvertEmpty
	4,  // 6: AdvertService.CreateAdvert:input_type -> CreateAdvertIn
	5,  // 7: AdvertService.CancelAdvert:input_type -> CancelAdvertIn
	6,  // 8: AdvertService.RestoreAdvert:input_type -> RestoreAdvertIn
	7,  // 9: AdvertService.EditAdvert:input_type -> EditAdvertIn
	2,  // 10: AdvertService.GetAdverts:output_type -> GetAdvertsOut
	0,  // 11: AdvertService.CreateAdvert:output_type -> AdvertEmpty
	0,  // 12: AdvertService.CancelAdvert:output_type -> AdvertEmpty
	0,  // 13: AdvertService.RestoreAdvert:output_type -> AdvertEmpty
	0,  // 14: AdvertService.EditAdvert:output_type -> AdvertEmpty
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_api_advert_proto_init() }
func file_api_advert_proto_init() {
	if File_api_advert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_advert_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_advert_proto_goTypes,
		DependencyIndexes: file_api_advert_proto_depIdxs,
		MessageInfos:      file_api_advert_proto_msgTypes,
	}.Build()
	File_api_advert_proto = out.File
	file_api_advert_proto_rawDesc = nil
	file_api_advert_proto_goTypes = nil
	file_api_advert_proto_depIdxs = nil
}
